"""
Builds the OpenXR test application (test/xr_triangle) for Android headsets and packages it as
two debuggable APKs, so the inspector's layer can be loaded into them (Android only loads layers
into debuggable applications):

    python tools/build_xr_triangle.py            # -> build/android/xr_triangle.apk, xr_triangle_slow.apk
    adb install -r build/android/xr_triangle.apk
    adb install -r build/android/xr_triangle_slow.apk

Both packages run the same library; the "slow" one (com.brendanduncan.xrtriangle.slow, "XR
Triangle (Slow)") renders the scene with deliberate inefficiencies for the inspector's frame
and shader analysis to flag.

Needs what tools/build_android.py needs (SDK with build-tools and a platform, NDK, cmake, ninja,
Java) plus glslc from the Vulkan SDK for the shaders. The Khronos OpenXR loader for Android is
downloaded from Maven Central into build/android/openxr on the first run.
"""
import argparse
import glob
import os
import shutil
import subprocess
import sys
import time
import urllib.request
import zipfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import build_android as ba  # noqa: E402

ROOT = ba.ROOT
OUT = os.path.join(ROOT, "build", "android")
SRC = os.path.join(ROOT, "test", "xr_triangle")
PACKAGE = "com.brendanduncan.xrtriangle"
# (package, label, apk name): the multiview application and its deliberately slow twin.
PACKAGES = [
    (PACKAGE, "XR Triangle", "xr_triangle.apk"),
    (PACKAGE + ".slow", "XR Triangle (Slow)", "xr_triangle_slow.apk"),
]
MIN_SDK = 29
TARGET_SDK = 32
LOADER_VERSION = "1.1.63"
LOADER_URL = f"https://repo1.maven.org/maven2/org/khronos/openxr/openxr_loader_for_android/{LOADER_VERSION}/openxr_loader_for_android-{LOADER_VERSION}.aar"


def find_glslc():
    for c in [shutil.which("glslc"), os.path.join(os.environ.get("VULKAN_SDK", ""), "Bin", "glslc" + ba.EXE),
              os.path.join(os.environ.get("VULKAN_SDK", ""), "bin", "glslc")]:
        if c and os.path.isfile(c):
            return c
    if ba.IS_WIN:
        found = ba.newest(glob.glob(r"C:\VulkanSDK\*"))
        if found and os.path.isfile(os.path.join(found, "Bin", "glslc.exe")):
            return os.path.join(found, "Bin", "glslc.exe")
    return None


def fetch_loader():
    """The OpenXR loader AAR: headers and per-ABI libraries."""
    d = os.path.join(OUT, "openxr")
    include = os.path.join(d, "prefab", "modules", "headers", "include")
    if os.path.isfile(os.path.join(include, "openxr", "openxr.h")):
        return d
    os.makedirs(d, exist_ok=True)
    aar = os.path.join(d, "loader.aar")
    print(f"downloading {LOADER_URL}")
    urllib.request.urlretrieve(LOADER_URL, aar)
    with zipfile.ZipFile(aar) as z:
        z.extractall(d)
    return d


def shaders_inl(glslc, out_dir):
    """Compiles the shaders and writes them as C arrays (shaders.inl)."""
    os.makedirs(out_dir, exist_ok=True)
    chunks = []
    for name, ident in (("xr.vert", "kVertSpv"), ("xr.frag", "kFragSpv"), ("xr_slow.frag", "kSlowFragSpv")):
        spv = os.path.join(out_dir, name + ".spv")
        ba.run([glslc, "--target-env=vulkan1.1", "-g", os.path.join(SRC, name), "-o", spv])
        with open(spv, "rb") as f:
            data = f.read()
        words = [int.from_bytes(data[i:i + 4], "little") for i in range(0, len(data), 4)]
        body = ",\n".join("    " + ", ".join(f"0x{w:08x}" for w in words[i:i + 8]) for i in range(0, len(words), 8))
        chunks.append(f"static const uint32_t {ident}[] = {{\n{body}\n}};\n")
    with open(os.path.join(out_dir, "shaders.inl"), "w", encoding="utf-8") as f:
        f.write("// generated by tools/build_xr_triangle.py\n#include <cstdint>\n" + "\n".join(chunks))


def build(abi, ndk, cmake, ninja, loader_dir, glslc, debug):
    build_dir = os.path.join(OUT, "xr_triangle", abi)
    shaders_inl(glslc, os.path.join(build_dir, "shaders"))
    loader = os.path.join(loader_dir, "jni", abi, "libopenxr_loader.so")
    if not os.path.isfile(loader):
        ba.die(f"no OpenXR loader for {abi} in {loader_dir}")
    ba.run([cmake, "-S", SRC, "-B", build_dir, "-G", "Ninja",
            f"-DCMAKE_MAKE_PROGRAM={ninja}",
            f"-DCMAKE_TOOLCHAIN_FILE={os.path.join(ndk, 'build', 'cmake', 'android.toolchain.cmake')}",
            f"-DANDROID_ABI={abi}",
            f"-DANDROID_PLATFORM=android-{MIN_SDK}",
            "-DANDROID_STL=c++_static",
            f"-DCMAKE_BUILD_TYPE={'Debug' if debug else 'RelWithDebInfo'}",
            f"-DOPENXR_INCLUDE={os.path.join(loader_dir, 'prefab', 'modules', 'headers', 'include')}",
            f"-DOPENXR_LOADER={loader}",
            f"-DSHADERS_DIR={os.path.join(build_dir, 'shaders')}"])
    ba.run([cmake, "--build", build_dir])
    lib = os.path.join(build_dir, "libxr_triangle.so")
    if not os.path.isfile(lib):
        ba.die(f"{lib} was not produced")
    return lib, loader


def package(libs, sdk, package_name, label, apk_name):
    build_tools = ba.newest(glob.glob(os.path.join(sdk, "build-tools", "*")))
    aapt2 = os.path.join(build_tools, "aapt2" + ba.EXE)
    zipalign = os.path.join(build_tools, "zipalign" + ba.EXE)
    apksigner = os.path.join(build_tools, "lib", "apksigner.jar")
    platform_dir = ba.newest(glob.glob(os.path.join(sdk, "platforms", "android-*")))
    android_jar = os.path.join(platform_dir, "android.jar")
    java = ba.find_java()
    if not java:
        ba.die("no Java runtime found for apksigner")
    work = os.path.join(OUT, "xr_triangle", "apk", package_name)
    os.makedirs(work, exist_ok=True)
    manifest = os.path.join(work, "AndroidManifest.xml")
    version_code = int(time.time()) // 60
    with open(manifest, "w", encoding="utf-8") as f:
        f.write(f'''<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="{package_name}"
    android:versionCode="{version_code}"
    android:versionName="1.0">
    <uses-sdk android:minSdkVersion="{MIN_SDK}" android:targetSdkVersion="{TARGET_SDK}"/>
    <uses-feature android:name="android.hardware.vr.headtracking" android:required="true" android:version="1"/>
    <uses-feature android:name="android.hardware.vulkan.level" android:required="true" android:version="1"/>
    <uses-permission android:name="org.khronos.openxr.permission.OPENXR"/>
    <uses-permission android:name="org.khronos.openxr.permission.OPENXR_SYSTEM"/>
    <!-- Hand tracking as an input option: the Quest shell otherwise refuses to launch the
         application until controllers are connected. -->
    <uses-feature android:name="oculus.software.handtracking" android:required="false"/>
    <uses-permission android:name="com.oculus.permission.HAND_TRACKING"/>
    <!-- The OpenXR loader finds the runtime through these brokers and services. -->
    <queries>
        <provider android:authorities="org.khronos.openxr.runtime_broker;org.khronos.openxr.system_runtime_broker"/>
        <intent><action android:name="org.khronos.openxr.OpenXRRuntimeService"/></intent>
        <intent><action android:name="org.khronos.openxr.OpenXRApiLayerService"/></intent>
    </queries>
    <!-- debuggable: Android loads GPU debug layers (the inspector's) only into debuggable applications. -->
    <application android:label="{label}"
        android:hasCode="false"
        android:debuggable="true"
        android:extractNativeLibs="true">
        <meta-data android:name="com.oculus.supportedDevices" android:value="quest|quest2|questpro|quest3|quest3s"/>
        <meta-data android:name="com.oculus.handtracking.version" android:value="V2.0"/>
        <activity android:name="android.app.NativeActivity"
            android:label="{label}"
            android:exported="true"
            android:launchMode="singleTask"
            android:screenOrientation="landscape"
            android:excludeFromRecents="false"
            android:configChanges="screenSize|screenLayout|orientation|keyboardHidden|keyboard|navigation|uiMode|density">
            <meta-data android:name="android.app.lib_name" android:value="xr_triangle"/>
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
                <category android:name="com.oculus.intent.category.VR"/>
                <category android:name="org.khronos.openxr.intent.category.IMMERSIVE_HMD"/>
            </intent-filter>
        </activity>
    </application>
</manifest>
''')
    unaligned = os.path.join(work, "unaligned.apk")
    aligned = os.path.join(work, "aligned.apk")
    for p in (unaligned, aligned):
        if os.path.exists(p):
            os.remove(p)
    ba.run([aapt2, "link", "-o", unaligned, "--manifest", manifest, "-I", android_jar,
            "--min-sdk-version", str(MIN_SDK), "--target-sdk-version", str(TARGET_SDK)])
    with zipfile.ZipFile(unaligned, "a", zipfile.ZIP_DEFLATED) as z:
        for abi, lib, loader in libs:
            z.write(lib, f"lib/{abi}/libxr_triangle.so")
            z.write(loader, f"lib/{abi}/libopenxr_loader.so")
    ba.run([zipalign, "-f", "4", unaligned, aligned])
    keystore = os.path.join(os.path.expanduser("~"), ".android", "debug.keystore")
    apk = os.path.join(OUT, apk_name)
    ba.run([java, "-jar", apksigner, "sign", "--ks", keystore, "--ks-pass", "pass:android",
            "--ks-key-alias", "androiddebugkey", "--key-pass", "pass:android", "--out", apk, aligned])
    print(f"apk: {apk} ({package_name})")


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    ap.add_argument("--abi", default="arm64-v8a")
    ap.add_argument("--sdk")
    ap.add_argument("--ndk")
    ap.add_argument("--debug", action="store_true")
    args = ap.parse_args()
    sdk = ba.find_sdk(args.sdk)
    ndk = ba.find_ndk(args.ndk, sdk)
    if not sdk or not ndk:
        ba.die("Android SDK / NDK not found")
    cmake, ninja = ba.find_cmake_tools(sdk)
    glslc = find_glslc()
    if not glslc:
        ba.die("glslc not found (install the Vulkan SDK or set VULKAN_SDK)")
    loader_dir = fetch_loader()
    libs = []
    for abi in [a.strip() for a in args.abi.split(",") if a.strip()]:
        lib, loader = build(abi, ndk, cmake, ninja, loader_dir, glslc, args.debug)
        libs.append((abi, lib, loader))
    for package_name, label, apk_name in PACKAGES:
        package(libs, sdk, package_name, label, apk_name)


if __name__ == "__main__":
    main()
