#!/usr/bin/env python3
"""Generates the D3D12 capture library's tables from the Windows SDK headers.

The D3D12 counterpart of gen_vulkan.py, with a much smaller job: D3D12 has no registry, so the
struct serializers are written by hand (d3d12/src/serialize.cpp), and what is generated here is
what would be hopeless to keep by hand:

  d3d12_enums.gen.h / .cpp   a name table for every enum of d3d12.h, d3d12sdklayers.h, d3dcommon.h
                             and the DXGI headers: ToString_<Enum>(value) and, for the enums the
                             headers give flag operators, Flags_<Enum>(writer, value) writing "A | B".
                             The tables hold names and numbers only, so they compile with any SDK.
  d3d12_vtables.gen.h        for the interfaces the library hooks, the vtable slot of every method
                             (slot::ID3D12GraphicsCommandList10::DrawInstanced) and a function pointer
                             typedef of its C signature (PFN_ID3D12GraphicsCommandList10_DrawInstanced),
                             read off the C-style vtable structs the headers carry for CINTERFACE.

Usage: gen_d3d12.py --sdk "<Windows Kits>/10/Include/<version>" --out d3d12/gen
"""
import argparse
import os
import re
import sys

# The interfaces whose vtables the library patches (d3d12/src/hook.h): the newest version of each,
# whose vtable holds every older version's methods first.
HOOKED_INTERFACES = [
    "ID3D12Object",
    "ID3D12Device14",
    "ID3D12GraphicsCommandList10",
    "ID3D12CommandQueue",
    "ID3D12CommandAllocator",
    "ID3D12Resource2",
    "ID3D12Heap1",
    "ID3D12DescriptorHeap",
    "ID3D12RootSignature",
    "ID3D12PipelineState",
    "ID3D12StateObject",
    "ID3D12Fence1",
    "ID3D12QueryHeap",
    "ID3D12CommandSignature",
    "ID3D12PipelineLibrary1",
    "IDXGIFactory7",
    "IDXGISwapChain4",
    "IDXGIAdapter4",
    "ID3D12InfoQueue1",
]

HEADERS = [
    "shared/dxgiformat.h", "shared/dxgicommon.h", "shared/dxgitype.h", "shared/dxgi.h",
    "shared/dxgi1_2.h", "shared/dxgi1_3.h", "shared/dxgi1_4.h", "shared/dxgi1_5.h", "shared/dxgi1_6.h",
    "um/d3dcommon.h", "um/d3d12.h", "um/d3d12sdklayers.h",
]


def read(path):
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        return f.read()


# ---------------------------------------------------------------------------------------------
# Enums

ENUM_RE = re.compile(r"typedef\s*\n?\s*enum\s+(\w+)\s*\{(.*?)\}\s*(\w+)\s*;", re.S)
FLAGS_RE = re.compile(r"DEFINE_ENUM_FLAG_OPERATORS\(\s*(\w+)\s*\)")


def strip_comments(text):
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    text = re.sub(r"//[^\n]*", "", text)
    return text


def parse_enums(text, known):
    """Returns [(name, [(entry, value)...])] in header order; `known` maps every constant seen so far."""
    out = []
    for m in ENUM_RE.finditer(text):
        name = m.group(1)
        body = m.group(2)
        entries = []
        next_value = 0
        for raw in body.split(","):
            item = raw.strip()
            if not item:
                continue
            if "=" in item:
                ename, expr = item.split("=", 1)
                ename = ename.strip()
                expr = expr.strip()
                # Header expressions: hex and decimal literals, shifts, ors, other constants.
                expr_py = re.sub(r"\b(\d+)[uUlL]+\b", r"\1", expr)
                expr_py = re.sub(r"\b(0x[0-9a-fA-F]+)[uUlL]+\b", r"\1", expr_py)
                try:
                    value = int(eval(expr_py, {"__builtins__": {}}, known))
                except Exception:
                    sys.stderr.write(f"gen_d3d12: cannot evaluate {ename} = {expr}\n")
                    continue
            else:
                ename = item
                value = next_value
            if not re.match(r"^\w+$", ename):
                continue
            if value >= 2 ** 63:
                value -= 2 ** 64
            entries.append((ename, value))
            known[ename] = value
            next_value = value + 1
        if entries:
            out.append((name, entries))
    return out


def emit_enums(enums, flags, out_dir):
    h = []
    cpp = []
    h.append("// Generated by tools/gen_d3d12.py from the Windows SDK headers: do not edit.\n")
    h.append("// Name tables of every D3D12, DXGI and debug-layer enum. Values only, so they compile with any SDK.\n")
    h.append("#pragma once\n#include <cstdint>\n\nnamespace vkinsp { class JsonWriter; }\n\nnamespace dxinsp {\n\n")
    h.append("struct EnumEntry { int64_t value; const char* name; };\n\n")
    h.append("/** The name of `value` in the table, or nullptr. */\nconst char* EnumName(const EnumEntry* entries, size_t count, int64_t value);\n")
    h.append("/** Writes a flags value as \"A | B\" from the single-bit entries of the table, an exact entry first, unknown bits in hex. */\n")
    h.append("void WriteFlags(vkinsp::JsonWriter& w, const EnumEntry* entries, size_t count, uint64_t value);\n\n")
    cpp.append("// Generated by tools/gen_d3d12.py from the Windows SDK headers: do not edit.\n")
    cpp.append('#include "d3d12_enums.gen.h"\n\n#include "json_writer.h"\n\n#include <cstdio>\n#include <string>\n\nnamespace dxinsp {\n\n')
    cpp.append("""const char* EnumName(const EnumEntry* entries, size_t count, int64_t value) {
    for (size_t i = 0; i < count; ++i)
        if (entries[i].value == value) return entries[i].name;
    return nullptr;
}

void WriteFlags(vkinsp::JsonWriter& w, const EnumEntry* entries, size_t count, uint64_t value) {
    if (const char* exact = EnumName(entries, count, (int64_t)value)) { w.String(exact); return; }
    std::string s;
    uint64_t rest = value;
    for (size_t i = 0; i < count && rest; ++i) {
        uint64_t bit = (uint64_t)entries[i].value;
        if (!bit || (bit & (bit - 1))) continue;   // zero, or a composite
        if (!(rest & bit)) continue;
        if (!s.empty()) s += " | ";
        s += entries[i].name;
        rest &= ~bit;
    }
    if (rest) {
        char buf[32];
        snprintf(buf, sizeof(buf), "0x%llx", (unsigned long long)rest);
        if (!s.empty()) s += " | ";
        s += buf;
    }
    if (s.empty()) s = "0";
    w.String(s);
}

""")
    for name, entries in enums:
        h.append(f"extern const EnumEntry kEnum_{name}[{len(entries)}];\n")
        h.append(f"inline const char* ToString_{name}(int64_t v) {{ return EnumName(kEnum_{name}, {len(entries)}, v); }}\n")
        if name in flags:
            h.append(f"inline void Flags_{name}(vkinsp::JsonWriter& w, uint64_t v) {{ WriteFlags(w, kEnum_{name}, {len(entries)}, v); }}\n")
        cpp.append(f"const EnumEntry kEnum_{name}[{len(entries)}] = {{\n")
        for ename, value in entries:
            cpp.append(f"    {{{value}LL, \"{ename}\"}},\n")
        cpp.append("};\n")
    h.append("\n}  // namespace dxinsp\n")
    cpp.append("\n}  // namespace dxinsp\n")
    write_if_changed(os.path.join(out_dir, "d3d12_enums.gen.h"), "".join(h))
    write_if_changed(os.path.join(out_dir, "d3d12_enums.gen.cpp"), "".join(cpp))


# ---------------------------------------------------------------------------------------------
# Vtables

VTBL_RE = re.compile(r"typedef struct (\w+)Vtbl\s*\{(.*?)\}\s*\1Vtbl\s*;", re.S)
METHOD_RE = re.compile(r"([\w\s\*]+?)\(\s*STDMETHODCALLTYPE\s*\*\s*(\w+)\s*\)\s*\((.*?)\)\s*;", re.S)


def drop_else_branches(body):
    """Keeps the first branch of every #if/#else in a vtable struct (the aggregate-return
    variants of GetDesc sit in an #else and occupy the same slot)."""
    out = []
    skipping = 0
    depth = 0
    for line in body.split("\n"):
        s = line.strip()
        if s.startswith("#if"):
            depth += 1
        elif s.startswith("#else") and depth and not skipping:
            skipping = depth
            continue
        elif s.startswith("#endif"):
            if skipping == depth:
                skipping = 0
            depth -= 1
            continue
        if skipping:
            continue
        if s.startswith("#"):
            continue
        out.append(line)
    return "\n".join(out)


def strip_sal(params):
    """Removes SAL annotations (_In_, _In_reads_(n), _COM_Outptr_, ...) from a parameter list."""
    out = []
    i = 0
    n = len(params)
    while i < n:
        m = re.match(r"_[A-Z][A-Za-z_]*_\b", params[i:])
        if m and (i == 0 or not (params[i - 1].isalnum() or params[i - 1] == "_")):
            i += m.end()
            # An argument list may follow: skip balanced parentheses.
            j = i
            while j < n and params[j] in " \t\n":
                j += 1
            if j < n and params[j] == "(":
                depth = 0
                while j < n:
                    if params[j] == "(":
                        depth += 1
                    elif params[j] == ")":
                        depth -= 1
                        if depth == 0:
                            j += 1
                            break
                    j += 1
                i = j
            continue
        out.append(params[i])
        i += 1
    text = "".join(out)
    text = re.sub(r"\s+", " ", text)
    text = re.sub(r"\s*,\s*", ", ", text)
    text = re.sub(r"\(\s+", "(", text)
    return text.strip()


def parse_vtables(text):
    out = {}
    for m in VTBL_RE.finditer(text):
        iface = m.group(1)
        body = drop_else_branches(m.group(2))
        methods = []
        for mm in METHOD_RE.finditer(body):
            ret = re.sub(r"\s+", " ", mm.group(1)).strip()
            ret = ret.replace("BEGIN_INTERFACE", "").replace("END_INTERFACE", "").strip()
            name = mm.group(2)
            params = strip_sal(mm.group(3))
            methods.append((ret, name, params))
        out[iface] = methods
    return out


def emit_vtables(vtables, out_dir):
    h = []
    h.append("// Generated by tools/gen_d3d12.py from the Windows SDK headers: do not edit.\n")
    h.append("// The vtable slot of every method of the interfaces the library hooks, and a typedef of its\n")
    h.append("// C signature for calling the original through the saved entry (d3d12/src/hook.h).\n")
    h.append("#pragma once\n\n#include <d3d12.h>\n#include <d3d12sdklayers.h>\n#include <dxgi1_6.h>\n\n#include <cstdint>\n\nnamespace dxinsp {\n\n")
    missing = [i for i in HOOKED_INTERFACES if i not in vtables]
    if missing:
        raise SystemExit(f"gen_d3d12: no vtable found for {', '.join(missing)}: is the SDK new enough?")
    h.append("namespace slot {\n")
    for iface in HOOKED_INTERFACES:
        methods = vtables[iface]
        h.append(f"enum {iface} : uint32_t {{\n")
        for i, (_ret, name, _params) in enumerate(methods):
            h.append(f"    {iface}_{name} = {i},\n")
        h.append(f"    {iface}_Count = {len(methods)}\n}};\n")
    h.append("}  // namespace slot\n\n")
    for iface in HOOKED_INTERFACES:
        for _i, (ret, name, params) in enumerate(vtables[iface]):
            h.append(f"typedef {ret} (STDMETHODCALLTYPE* PFN_{iface}_{name})({params});\n")
        h.append("\n")
    h.append("}  // namespace dxinsp\n")
    write_if_changed(os.path.join(out_dir, "d3d12_vtables.gen.h"), "".join(h))


def write_if_changed(path, content):
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            if f.read() == content:
                return
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)


def find_sdk():
    """The newest Windows 10/11 SDK include directory on this machine."""
    roots = [os.path.join(os.environ.get("ProgramFiles(x86)", r"C:\Program Files (x86)"), "Windows Kits", "10", "Include")]
    if os.environ.get("WindowsSdkDir"):
        roots.insert(0, os.path.join(os.environ["WindowsSdkDir"], "Include"))
    for root in roots:
        if not os.path.isdir(root):
            continue
        versions = sorted((v for v in os.listdir(root) if re.match(r"^\d+\.", v) and os.path.exists(os.path.join(root, v, "um", "d3d12.h"))),
                          key=lambda v: [int(x) for x in v.split(".")], reverse=True)
        if versions:
            return os.path.join(root, versions[0])
    return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--sdk", help="Windows SDK include directory (the one holding um/ and shared/)")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()
    sdk = args.sdk or find_sdk()
    if not sdk or not os.path.exists(os.path.join(sdk, "um", "d3d12.h")):
        raise SystemExit("gen_d3d12: Windows SDK not found (pass --sdk)")
    os.makedirs(args.out, exist_ok=True)
    enums = []
    flags = set()
    vtables = {}
    known = {}
    for rel in HEADERS:
        path = os.path.join(sdk, rel)
        if not os.path.exists(path):
            sys.stderr.write(f"gen_d3d12: {path} not found, skipping\n")
            continue
        text = strip_comments(read(path))
        enums.extend(parse_enums(text, known))
        flags.update(FLAGS_RE.findall(text))
        vtables.update(parse_vtables(text))
    seen = set()
    unique = []
    for name, entries in enums:
        if name in seen:
            continue
        seen.add(name)
        unique.append((name, entries))
    emit_enums(unique, flags, args.out)
    emit_vtables(vtables, args.out)
    print(f"gen_d3d12: {len(unique)} enums, {len(HOOKED_INTERFACES)} vtables from {sdk}")


if __name__ == "__main__":
    main()
