#!/usr/bin/env python3
"""Compiles the in-app HUD's shaders and writes them as committed C headers.

Two backends need this: the Vulkan layer's SPIR-V (glslc, from hud.vert and hud.frag) and the
D3D12 library's DXBC (fxc, from hud.hlsl). Metal is not here -- it compiles its MSL at run time
from a string in the source, which Vulkan and D3D12 cannot do.

These headers are generated by hand and checked in, unlike src/vulkan/gen, which CMake regenerates
on every build. A release build has no shader compiler: the Vulkan SDK and glslc are needed only
for the tests, and .github/workflows/release.yml configures with VKINSP_BUILD_TESTS=OFF precisely
so the installer can be built without them. Compiling the HUD at build time would put the SDK, and
on Windows the DirectX compiler too, back on the critical path for everyone.

So: run this on a machine that has the compilers, and commit what it writes.

    python tools/gen_hud_shaders.py

It is idempotent -- both compilers are deterministic for the same source -- so a run that changes
nothing means the committed headers are current, which is what --check tests.

Usage:
    python tools/gen_hud_shaders.py [--glslc <path>] [--fxc <path>] [--check] [--skip-d3d12]
"""

import argparse
import hashlib
import os
import shutil
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VK_DIR = os.path.join(ROOT, "src", "vulkan", "shaders")
VK_OUT = os.path.join(VK_DIR, "hud_shaders.gen.h")
DX_DIR = os.path.join(ROOT, "src", "d3d12", "shaders")
DX_OUT = os.path.join(DX_DIR, "hud_shaders.gen.h")

# (source file, C identifier, glslc stage)
VK_SHADERS = [
    ("hud.vert", "kHudVertSpv", "vert"),
    ("hud.frag", "kHudFragSpv", "frag"),
]

# (entry point, C identifier, fxc profile). Shader model 5.1 and DXBC rather than dxc and DXIL:
# DXBC is accepted by every D3D12 driver, needs no separate signing step, and these two shaders use
# nothing that would want a newer model.
DX_SHADERS = [
    ("VSMain", "kHudVertDxbc", "vs_5_1"),
    ("PSMain", "kHudPixelDxbc", "ps_5_1"),
]

# The line the generated headers carry their source hash on, for --check-sources.
SOURCE_MARKER = "sources sha256: "

WINDOWS_KITS = [
    os.path.join("C:" + os.sep, "Program Files (x86)", "Windows Kits", "10", "bin"),
    os.path.join("C:" + os.sep, "Program Files", "Windows Kits", "10", "bin"),
]


def find_glslc(explicit):
    if explicit:
        return explicit
    found = shutil.which("glslc")
    if found:
        return found
    sdk = os.environ.get("VULKAN_SDK")
    if sdk:
        for name in ("glslc.exe", "glslc"):
            candidate = os.path.join(sdk, "Bin", name)
            if os.path.exists(candidate):
                return candidate
    return None


def find_fxc(explicit):
    """fxc ships with the Windows SDK, one copy per installed version; the newest wins."""
    if explicit:
        return explicit
    found = shutil.which("fxc")
    if found:
        return found
    candidates = []
    for root in WINDOWS_KITS:
        if not os.path.isdir(root):
            continue
        for version in os.listdir(root):
            candidate = os.path.join(root, version, "x64", "fxc.exe")
            if os.path.exists(candidate):
                candidates.append((version, candidate))
    return sorted(candidates)[-1][1] if candidates else None


def compile_spirv(glslc, path, stage):
    """The SPIR-V words of one shader, as a list of ints."""
    with tempfile.TemporaryDirectory() as tmp:
        out = os.path.join(tmp, "out.spv")
        # -O for size: these shaders are tiny either way, but the optimizer also drops the debug
        # information glslc emits by default, which is the bulk of an unoptimized module.
        cmd = [glslc, "-O", f"-fshader-stage={stage}", "--target-env=vulkan1.0", path, "-o", out]
        proc = subprocess.run(cmd, capture_output=True, text=True)
        if proc.returncode != 0:
            sys.stderr.write(proc.stdout + proc.stderr)
            raise SystemExit(f"glslc failed on {os.path.basename(path)}")
        with open(out, "rb") as f:
            data = f.read()
    if len(data) % 4:
        raise SystemExit(f"{path}: SPIR-V is not a whole number of words")
    return [int.from_bytes(data[i:i + 4], "little") for i in range(0, len(data), 4)]


def compile_dxbc(fxc, path, entry, profile):
    """The DXBC bytes of one shader."""
    with tempfile.TemporaryDirectory() as tmp:
        out = os.path.join(tmp, "out.cso")
        # /O3 and no debug info, for the same reason as -O above. /Qstrip_reflect keeps the blob to
        # what the runtime needs: the input layout is declared in C++, not read back from here.
        cmd = [fxc, "/nologo", "/T", profile, "/E", entry, "/O3", "/Qstrip_reflect", "/Fo", out, path]
        proc = subprocess.run(cmd, capture_output=True, text=True)
        if proc.returncode != 0:
            sys.stderr.write(proc.stdout + proc.stderr)
            raise SystemExit(f"fxc failed on {entry}")
        with open(out, "rb") as f:
            return f.read()


def source_digest(paths):
    """A hash of the shader sources a header was built from.

    Written into the header so that --check-sources can tell, without a shader compiler, whether a
    shader has been edited since the header was generated. That is the mistake worth catching, and
    the one CI can catch: it deliberately has neither glslc nor fxc, so it cannot recompile and
    compare, but it can read two files and hash them. Line endings are normalised so a checkout
    with CRLF does not look like an edit.
    """
    digest = hashlib.sha256()
    for path in paths:
        with open(path, "rb") as f:
            digest.update(f.read().replace(b"\r\n", b"\n"))
    return digest.hexdigest()


def header(lines, source, namespace, digest):
    return "\n".join([
        "// GENERATED FILE - do not edit. Produced by tools/gen_hud_shaders.py from",
        f"// {source} beside it.",
        "//",
        "// Committed rather than built, because a release build has no shader compiler (the SDKs",
        "// are needed only for the tests, which the release workflow turns off). Regenerate with",
        "//     python tools/gen_hud_shaders.py",
        "// after editing the shader, and commit the result.",
        "//",
        f"// {SOURCE_MARKER}{digest}",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        f"namespace {namespace} {{",
        "",
        *lines,
        f"}} // namespace {namespace}",
        "",
    ])


def render_spirv(modules, digest):
    lines = []
    for (src, name, _stage), words in modules:
        lines.append(f"// {src}, {len(words)} words")
        lines.append(f"static const uint32_t {name}[] = {{")
        for i in range(0, len(words), 8):
            lines.append("    " + ", ".join(f"0x{w:08x}" for w in words[i:i + 8]) + ",")
        lines.append("};")
        lines.append("")
    return header(lines, "hud.vert and hud.frag", "vkinsp", digest)


def render_dxbc(modules, digest):
    lines = []
    for (entry, name, profile), data in modules:
        lines.append(f"// {entry} ({profile}), {len(data)} bytes")
        lines.append(f"static const uint8_t {name}[] = {{")
        for i in range(0, len(data), 12):
            lines.append("    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 12]) + ",")
        lines.append("};")
        lines.append("")
    return header(lines, "hud.hlsl", "dxinsp", digest)


def write(path, text, check):
    existing = None
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8", newline="") as f:
            existing = f.read()
    relative = os.path.relpath(path, ROOT)
    if check:
        if existing != text:
            raise SystemExit(f"{relative} is stale: rerun tools/gen_hud_shaders.py")
        print(f"{relative} is current")
        return
    if existing == text:
        print(f"{relative} unchanged")
        return
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(f"wrote {relative}")


def check_sources():
    """Every committed header still matches the shader it was generated from. Needs no compiler."""
    stale = []
    for out, sources in ((VK_OUT, [os.path.join(VK_DIR, s[0]) for s in VK_SHADERS]),
                         (DX_OUT, [os.path.join(DX_DIR, "hud.hlsl")])):
        relative = os.path.relpath(out, ROOT)
        if not os.path.exists(out):
            stale.append(f"{relative} is missing")
            continue
        with open(out, "r", encoding="utf-8") as f:
            recorded = next((line.split(SOURCE_MARKER, 1)[1].strip()
                             for line in f if SOURCE_MARKER in line), None)
        if recorded is None:
            stale.append(f"{relative} records no source hash")
        elif recorded != source_digest(sources):
            stale.append(f"{relative} was generated from a different version of "
                         f"{', '.join(os.path.basename(s) for s in sources)}")
        else:
            print(f"{relative} matches its shader source")
    if stale:
        raise SystemExit("\n".join(stale + [
            "", "A HUD shader was edited without regenerating its header. On a machine with the",
            "Vulkan SDK and (for D3D12) the Windows SDK:", "",
            "    python tools/gen_hud_shaders.py", "", "and commit the result.",
        ]))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--glslc", help="path to glslc (default: PATH, then $VULKAN_SDK/Bin)")
    ap.add_argument("--fxc", help="path to fxc (default: PATH, then the newest Windows SDK)")
    ap.add_argument("--check", action="store_true", help="fail if a committed header is stale")
    ap.add_argument("--check-sources", action="store_true",
                    help="fail if a shader was edited without regenerating its header; needs no "
                         "compiler, which is what lets CI run it")
    ap.add_argument("--skip-d3d12", action="store_true",
                    help="Vulkan only, for a machine with no Windows SDK")
    args = ap.parse_args()

    if args.check_sources:
        check_sources()
        return

    glslc = find_glslc(args.glslc)
    if not glslc:
        raise SystemExit("glslc not found: install the Vulkan SDK, or pass --glslc")
    vk_sources = [os.path.join(VK_DIR, s[0]) for s in VK_SHADERS]
    write(VK_OUT, render_spirv([(s, compile_spirv(glslc, os.path.join(VK_DIR, s[0]), s[2]))
                                for s in VK_SHADERS], source_digest(vk_sources)), args.check)

    if args.skip_d3d12:
        return
    fxc = find_fxc(args.fxc)
    if not fxc:
        raise SystemExit("fxc not found: install the Windows SDK, pass --fxc, or use --skip-d3d12")
    source = os.path.join(DX_DIR, "hud.hlsl")
    write(DX_OUT, render_dxbc([(s, compile_dxbc(fxc, source, s[0], s[2])) for s in DX_SHADERS],
                              source_digest([source])), args.check)


if __name__ == "__main__":
    main()
